title: Joel W Smith
description: Resources and recommended gear for live streaming, cinematic filmmaking, and video production.
remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
